---
- name: Launch Docker Container on Remote VM
  hosts: prod
  vars:
    docker_image: "{{ lookup('env', 'JOB_NAME') }}"
    docker_tag: "{{ lookup('env', 'BUILD_ID') }}"
    container_name: "con1"
    host_port: "8000"
    container_port: "8000"
  tasks:
    - name: Load Docker image from tarball
      shell: docker load -i /root/{{ docker_image }}-{{ docker_tag }}.tar.gz

    - name: Stop and remove old container (if exists)
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Run the new Docker Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        published_ports: "{{ host_port }}:{{ container_port }}"
